"""Digest editorializer applying a strict 1-to-1 presentation overlay on canonical StoryCards (Plan 5 Task 5)."""

from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass, replace
from typing import Any

from src.ai_providers import AIProvider, create_provider
from src.config_loader import Config, load_config
from src.editorial_input import PreparedBundle
from src.editorial_models import StoryCard, is_expected_language
from src.publication.editorial_adapter import DatabaseGenerationAttemptObserver

logger = logging.getLogger(__name__)

DIGEST_EDITORIALIZER_PROMPT_VERSION = "digest-editorializer-v1"


@dataclass(frozen=True)
class PresentationOverlay:
    """Strict presentation overlay generated by LLM over a canonical StoryCard."""

    id: str
    topic: str
    summary: str


class EditorializationError(RuntimeError):
    """Raised when structural or provider failure occurs during digest editorialization."""


class DigestEditorializer:
    """Applies strict 1-to-1 LLM presentation overlay (topic, category, summary) over canonical cards."""

    def __init__(
        self,
        *,
        provider: AIProvider | None = None,
        config: Config | None = None,
        model_name: str | None = None,
    ) -> None:
        self.config = config or load_config()
        self.model_name = (
            model_name or self.config.settings.ai_model or self.config.settings.openai_model
        )
        if provider is not None:
            self.provider = provider
        else:
            try:
                self.provider = create_provider(
                    self.config.settings.ai_provider,
                    logger=logger,
                    openai_api_key=self.config.openai_api_key,
                    openai_base_url=getattr(self.config.settings, "openai_base_url", ""),
                    anthropic_api_key=self.config.anthropic_api_key,
                    google_api_key=getattr(self.config, "gemini_api_key", "")
                    or getattr(self.config, "google_api_key", ""),
                    google_api_keys=getattr(self.config, "google_api_keys", None),
                    openrouter_api_key=getattr(self.config, "openrouter_api_key", ""),
                    openrouter_base_url=getattr(
                        self.config.settings, "openrouter_base_url", "https://openrouter.ai/api/v1"
                    ),
                    openrouter_model=getattr(
                        self.config.settings, "openrouter_model", "openrouter/free"
                    ),
                    ollama_base_url=self.config.settings.ollama_base_url,
                    api_timeout=self.config.settings.api_timeout,
                    reasoning_effort=getattr(self.config.settings, "reasoning_effort", None),
                )
            except Exception as exc:
                logger.warning(
                    "Could not initialize AI provider %s: %s",
                    self.config.settings.ai_provider,
                    exc,
                )
                from src.publication.selection_ai import _NullAIProvider

                self.provider = _NullAIProvider()

    async def editorialize(
        self,
        *,
        cards: list[StoryCard],
        bundle: PreparedBundle,
        attempt_observer: DatabaseGenerationAttemptObserver | None = None,
    ) -> list[StoryCard]:
        """Apply presentation overlays to cards while strictly preserving cardinality, evidence, and order."""
        if not cards:
            return []

        payload = self._build_payload(cards, bundle)
        prompt_text = json.dumps(payload, ensure_ascii=False, indent=2)
        prompt_bytes = json.dumps(payload, ensure_ascii=False, sort_keys=True).encode("utf-8")
        prompt_hash = hashlib.sha256(prompt_bytes).hexdigest()

        att_id = None
        if attempt_observer is not None:
            provider_name = getattr(self.provider, "name", self.config.settings.ai_provider)
            att_id = await attempt_observer.attempt_started(
                "writer",
                provider=provider_name,
                model=self.model_name,
                prompt_hash=prompt_hash,
                metadata={
                    "subkind": "digest_editorializer",
                    "prompt_version": DIGEST_EDITORIALIZER_PROMPT_VERSION,
                    "card_count": len(cards),
                },
            )

        system_prompt = (
            "You are a professional presentation editor for a regional news digest. "
            "Your task is to refine and synthesize the wording of each story card.\n\n"
            "INVARIANTS & CONSTRAINTS:\n"
            "1. You are a presentation editor, NOT a story selector.\n"
            "2. For each input story ID, output exactly one overlay improving ONLY:\n"
            "   - 'topic': specific, concise, journalistic headline (do NOT use generic 'Городские события').\n"
            "   - 'summary': clear, cohesive editorial synthesis in Russian.\n"
            "3. Improve only topic and summary. Do not classify the story into a digest section; section assignment is performed separately.\n"
            "4. NEVER add, remove, merge, split, or reorder stories.\n"
            "5. NEVER invent facts or include claims not present in the supplied evidence for that story ID.\n"
            "6. When a story has only community observations, do NOT state them as established official facts.\n"
            "7. Keep practical details (schedules, addresses, prices, contacts) in summary or separate details.\n"
            "8. Respond strictly with a JSON object containing an 'overlays' array."
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": f"Please editorialize these {len(cards)} story cards:\n{prompt_text}",
            },
        ]

        try:
            raw_output = await self.provider.chat_completion(
                messages=messages,
                model=self.model_name,
                temperature=0.2,
                max_tokens=4096,
            )
            overlays_by_id = self._parse_overlays(raw_output, cards)
            result = self._merge_overlays(cards, overlays_by_id)

            if attempt_observer is not None and att_id is not None:
                await attempt_observer.attempt_finished(att_id, "succeeded")

            return result
        except Exception as exc:
            if attempt_observer is not None and att_id is not None:
                await attempt_observer.attempt_finished(
                    att_id, "failed", error_kind=type(exc).__name__
                )
            if isinstance(exc, EditorializationError):
                raise
            raise EditorializationError(f"editorializer provider failed: {exc}") from exc

    def _build_payload(
        self, cards: list[StoryCard], bundle: PreparedBundle
    ) -> list[dict[str, Any]]:
        payload: list[dict[str, Any]] = []
        for card in cards:
            card_refs = sorted(card.all_source_refs())
            card_sources = {
                ref: {
                    "name": bundle.records[ref].message.channel_name,
                    "timestamp": (
                        bundle.records[ref].message.timestamp.isoformat()
                        if bundle.records[ref].message.timestamp
                        else None
                    ),
                    "context": bundle.records[ref].context_text,
                }
                for ref in card_refs
                if ref in bundle.records
            }
            payload.append(
                {
                    "id": card.id,
                    "current_topic": card.topic,
                    "current_category": card.category,
                    "current_summary": card.summary,
                    "tags": list(card.tags),
                    "hard_facts": [
                        {
                            "text": item.text,
                            "status": item.status,
                            "attribution": item.attribution,
                            "source_refs": item.source_refs,
                        }
                        for item in card.hard_facts
                    ],
                    "community_observations": [
                        {
                            "text": item.text,
                            "status": item.status,
                            "attribution": item.attribution,
                            "source_refs": item.source_refs,
                        }
                        for item in card.community_observations
                    ],
                    "useful_details": [
                        {
                            "text": item.text,
                            "status": item.status,
                            "attribution": item.attribution,
                            "source_refs": item.source_refs,
                        }
                        for item in card.useful_details
                    ],
                    "uncertainties": [
                        {
                            "text": item.text,
                            "basis": item.basis,
                            "related_source_refs": item.related_source_refs,
                        }
                        for item in card.uncertainties
                    ],
                    "sources": card_sources,
                }
            )
        return payload

    def _parse_overlays(
        self, raw_output: str, cards: list[StoryCard]
    ) -> dict[str, PresentationOverlay]:
        text = raw_output.strip()
        if text.startswith("```"):
            text = re.sub(r"^```(?:json)?\n?", "", text)
            text = re.sub(r"\n?```$", "", text).strip()

        try:
            data = json.loads(text)
        except Exception as err:
            raise EditorializationError(f"failed to parse editorializer JSON: {err}") from err

        if not isinstance(data, dict):
            raise EditorializationError(f"expected JSON object root, got {type(data).__name__}")

        raw_list = data.get("overlays") or data.get("cards")
        if not isinstance(raw_list, list):
            raise EditorializationError("JSON response missing 'overlays' list")

        expected_ids = {c.id for c in cards}
        seen_ids: set[str] = set()
        overlays_by_id: dict[str, PresentationOverlay] = {}
        expected_lang = getattr(self.config.settings, "output_language", "Russian")

        for item in raw_list:
            if not isinstance(item, dict):
                raise EditorializationError("each overlay item must be a JSON object")

            raw_id = str(item.get("id", "")).strip()
            if not raw_id:
                raise EditorializationError("overlay item missing required 'id'")

            if raw_id not in expected_ids:
                raise EditorializationError(f"unknown story ID in editorializer response: {raw_id}")

            if raw_id in seen_ids:
                raise EditorializationError(
                    f"duplicate story ID in editorializer response: {raw_id}"
                )
            seen_ids.add(raw_id)

            topic = str(item.get("topic", "")).strip()
            summary = str(item.get("summary", "")).strip()

            # Card-level validation: if individual fields are invalid, fallback that card
            if not topic or not summary:
                logger.warning(
                    "overlay for story %s has empty topic or summary; falling back to canonical card",
                    raw_id,
                )
                continue

            combined_text = f"{topic} {summary}"
            if not is_expected_language(combined_text, expected_lang):
                logger.warning(
                    "overlay for story %s failed output language check (%s); falling back to canonical card",
                    raw_id,
                    expected_lang,
                )
                continue

            overlays_by_id[raw_id] = PresentationOverlay(
                id=raw_id,
                topic=topic,
                summary=summary,
            )

        return overlays_by_id

    def _merge_overlays(
        self, cards: list[StoryCard], overlays_by_id: dict[str, PresentationOverlay]
    ) -> list[StoryCard]:
        result: list[StoryCard] = []
        for card in cards:
            overlay = overlays_by_id.get(card.id)
            if overlay is not None:
                merged_card = replace(
                    card,
                    topic=overlay.topic,
                    summary=overlay.summary,
                )
                result.append(merged_card)
            else:
                result.append(card)
        return result
